services:
  frontend:
    image: ghcr.io/marketplaceservicios/vive-silver-frontend:latest
    pull_policy: always
    container_name: vive-silver-frontend
    restart: always
    networks:
      - proxy
networks:
  proxy:
    external: true
